const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
const rivals=[['Sugar Rush','Baby Baby'],['The Wild Ones','Crazy Tonight'],['Electric Blue','Without You'],['Velvet Rope','Poison Kiss'],['Satellite Girls','All Night'],['Northstar','Back To You'],['Honey Club','Telephone Heart'],['Juliet X','Crash Landing'],['The Polaroids','Summer Skin'],['The Daydreams','Satellite Heart']];
const S={band:'Neon Saints',month:0,year:1,week:1,cash:50000,fans:0,hype:5,chem:75,fame:0,actions:3,songs:[],event:false,feed:['A tiny label has taken a chance on your new group.','Your first rehearsal starts today.'],members:[{name:'Maya',role:'Lead singer',v:92,s:74,c:96,trait:'Drama Queen',heart:72,color:'#ff4f93'},{name:'Chloe',role:'Dancer / vocals',v:71,s:94,c:83,trait:'Ambitious',heart:78,color:'#9064dc'},{name:'Jade',role:'Harmony vocals',v:87,s:68,c:76,trait:'Peacemaker',heart:84,color:'#20c9bd'}]};
const clamp=n=>Math.max(0,Math.min(100,n)), fmt=n=>'$'+Math.round(n).toLocaleString();
function news(t){S.feed.unshift(t);S.feed=S.feed.slice(0,5)}
function render(){ $('#cash').textContent=fmt(S.cash);$('#fans').textContent=S.fans.toLocaleString();$('#hype').textContent=S.hype;$('#chemistry').textContent=S.chem;$('#fame').textContent=S.fame;$('#actions').textContent=S.actions;$('#available').textContent=S.actions+'/3 AVAILABLE';$('#week').textContent='WEEK '+S.week;$('#yearMonth').textContent='YEAR '+S.year+' · '+months[S.month].toUpperCase();$('#headline').textContent=S.feed[0];$('#chartDate').textContent=months[S.month]+' '+(1996+S.year);$('#chemRing').textContent=S.chem;$$('.band').forEach(x=>x.textContent=S.band.toUpperCase());renderSongs();renderFeed();renderChart();renderMembers();disableActions()}
function renderFeed(){$('#feed').innerHTML=S.feed.map((x,i)=>`<p><b>${i?'PAST':'NOW'}</b><span>${x}</span></p>`).join('')}
function renderSongs(){const box=$('#songs');$('#songCount').textContent=S.songs.length+' SONG'+(S.songs.length===1?'':'S');if(!S.songs.length)return;box.className='songList';box.innerHTML=S.songs.map((s,i)=>`<article><i>♪</i><span><b>${s.title}</b><small>${s.released?'#'+s.pos+' · Peak #'+s.peak:'Quality '+s.quality+' · Ready'}</small></span>${s.released?'':`<button data-release="${i}">RELEASE</button>`}</article>`).join('');$$('[data-release]').forEach(b=>b.onclick=()=>release(+b.dataset.release))}
function renderChart(){let rows=rivals.map((r,i)=>({act:r[0],title:r[1],pos:i+1,player:false}));const s=S.songs.find(x=>x.released);if(s)rows.push({act:S.band.toUpperCase(),title:s.title,pos:s.pos,player:true});rows.sort((a,b)=>a.pos-b.pos);$('#chart').innerHTML=rows.slice(0,10).map((r,i)=>`<article class="${r.player?'player':''}"><b>${r.pos}</b><i>${i%3===0?'▲':i%3===1?'▼':'—'}</i><span><strong>${r.title}</strong><small>${r.act}</small></span>${r.player?'<mark>YOUR SINGLE</mark>':''}</article>`).join('')}
function meter(label,n){return `<div class="meter"><span><b>${label}</b><strong>${n}</strong></span><i><u style="width:${n}%"></u></i></div>`}
function renderMembers(){$('#members').innerHTML=S.members.map((m,i)=>`<article class="panel member"><div class="portrait" style="background:${m.color}"><b>${m.name[0]}</b><i>0${i+1}</i></div><section><small>${m.role}</small><h3>${m.name}</h3><mark>${m.trait}</mark>${meter('VOCALS',m.v)}${meter('STAGE',m.s)}${meter('CHARISMA',m.c)}<footer><b>♥ LOYALTY</b><strong>${m.heart}</strong></footer></section></article>`).join('')}
function disableActions(){$$('[data-action]').forEach(b=>b.disabled=S.actions<1);const video=$('[data-action="video"]');if(video)video.disabled=S.actions<1||!S.songs.some(x=>x.released)||S.cash<15000}
function spend(cost,fn){if(S.actions<1||S.cash<cost)return;S.cash-=cost;S.actions--;fn();render()}
function open(html,locked=false){$('#modalBody').innerHTML=(locked?'':'<button class="close">×</button>')+html;$('#modal').classList.remove('hidden');if(!locked)$('.close').onclick=close}
function close(){$('#modal').classList.add('hidden')}
function record(){open(`<div class="kicker">STUDIO SESSION</div><h2>RECORD A <i>NEW SINGLE</i></h2><p>Name the song the world will remember.</p><label>SONG TITLE</label><input id="songTitle" value="Never Let Me Go" maxlength="28"><div class="production"><span>PRODUCTION<b>PREMIUM POP</b></span><strong>$22,000</strong></div><button class="primary" id="recordNow">ENTER THE STUDIO →</button>`);$('#recordNow').onclick=()=>{const title=$('#songTitle').value.trim();if(!title||S.cash<22000||S.actions<1)return;S.cash-=22000;S.actions--;S.hype=clamp(S.hype+8);S.songs.push({title,quality:68+Math.floor(Math.random()*24),catchy:70+Math.floor(Math.random()*25),released:false,pos:100,peak:100,weeks:0});news(`“${title}” is mastered and ready to release.`);close();render()}}
function release(i){if(S.actions<1)return;S.actions--;Object.assign(S.songs[i],{released:true,pos:73,peak:73,weeks:1});S.hype=clamp(S.hype+12);news('Release day! Your single enters the chart at #73.');show('charts');render()}
function doAction(a){if(a==='record')return record();if(a==='promo')spend(8000,()=>{S.hype=clamp(S.hype+22);S.fans+=1800;news('Your press campaign is everywhere. People are starting to talk.')});if(a==='video')spend(15000,()=>{S.hype=clamp(S.hype+30);S.fans+=3500;news('The new video premieres on MTV—and the phones light up.')});if(a==='show')spend(4000,()=>{S.fans+=2200;S.chem=clamp(S.chem+3);S.hype=clamp(S.hype+9);news('A sweaty club show earns the band hundreds of new believers.')});if(a==='photo')spend(6000,()=>{S.fame=clamp(S.fame+5);S.hype=clamp(S.hype+12);news('Your first magazine cover hits the newsstands.')});if(a==='break')spend(0,()=>{S.chem=clamp(S.chem+14);S.members.forEach(m=>m.heart=clamp(m.heart+8));news('A quiet week away helps everyone remember why they started.')})}
function next(){S.week++;if(S.week===5){S.week=1;S.month++;S.actions=3;S.cash-=2500;if(S.month===12){awards();S.month=0;S.year++}}S.songs.filter(x=>x.released).forEach(s=>{const oldPeak=s.peak,push=Math.max(2,Math.round((s.quality+s.catchy+S.hype)/18+Math.random()*7));s.pos=Math.max(1,s.pos-push);s.peak=Math.min(s.peak,s.pos);s.weeks++;if(s.pos===1&&oldPeak!==1){S.fans+=42000;S.fame=clamp(S.fame+22);news(`🏆 “${s.title}” is your first #1 single!`)}else news(`“${s.title}” moves to #${s.pos} on the chart.`)});S.fans+=Math.max(80,S.hype*22);S.hype=clamp(S.hype-2);if(!S.event&&S.month>=2&&S.week===2)crisis();render()}
function crisis(){open(`<div class="alert">BAND CRISIS</div><h2>MAYA WON’T <i>SING IT.</i></h2><p class="story">Maya refuses to perform the new single. She calls it “plastic, obvious, and beneath us.” The label needs an answer tonight.</p><div class="choices"><button data-choice="0"><b>A</b><span><strong>Replace the song</strong><small>−$20K · Maya ♥ +15</small></span></button><button data-choice="1"><b>B</b><span><strong>She’s under contract</strong><small>Maya ♥ −25 · Chemistry −10</small></span></button><button data-choice="2"><b>C</b><span><strong>Let Chloe sing lead</strong><small>Hype +18 · Chloe ♥ +20 · ???</small></span></button></div>`,true);$$('[data-choice]').forEach(b=>b.onclick=()=>choice(+b.dataset.choice))}
function choice(c){S.event=true;if(c===0){S.cash-=20000;S.members[0].heart=clamp(S.members[0].heart+15);news('You replace the single. Maya feels heard—but the label is nervous.')}if(c===1){S.chem=clamp(S.chem-10);S.members[0].heart=clamp(S.members[0].heart-25);news('Maya performs under protest. The tension backstage is impossible to miss.')}if(c===2){S.chem=clamp(S.chem-4);S.hype=clamp(S.hype+18);S.members[1].heart=clamp(S.members[1].heart+20);news('Chloe takes the lead—and the press calls it a bold reinvention.')}close();render()}
function awards(){const win=S.fans>25000;open(`<div class="award">★</div><div class="kicker">POP MUSIC AWARDS · ${1996+S.year}</div><h2>AND THE WINNER IS…<br><i>${win?S.band:'SUGAR RUSH'}!</i></h2><p>${win?'Best New Artist. Your first trophy—and proof this is only the beginning.':'Not this year. The sting follows you all the way home.'}</p><button id="newYear" class="primary">BEGIN YEAR ${S.year+1} →</button>`,true);$('#newYear').onclick=()=>{close();news(`Year ${S.year+1} begins. The world expects more from you now.`);render()}}
function show(v){$$('.page').forEach(x=>x.classList.toggle('hidden',x.id!==v));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v))}
$('#start').onclick=()=>{S.band=$('#bandName').value.trim()||'Neon Saints';$('#opening').classList.add('hidden');$('#game').classList.remove('hidden');render()};$('#next').onclick=next;$$('[data-view]').forEach(x=>x.onclick=()=>show(x.dataset.view));$$('[data-action]').forEach(x=>x.onclick=()=>doAction(x.dataset.action));$('#modal').onclick=e=>{if(e.target===$('#modal'))close()};render();
