(()=>{
  const SAVE_KEY='popDynastyMobileV1';
  const META_KEY='popDynastyProgressV1';
  let meta={unlockedRoles:[],completedCareers:0};
  let weekTimer=null;
  let toastQueue=null;
  const firstNames={girl:['Jade','Maya','Chloe','Nina','Zoe','Lena','Alexis','Tara'],boy:['Chris','Alex','Leo','Noah','Jesse','Dylan','Ryan','Kai']};
  const bandNames={girl:['Neon Hearts','Velvet Crush','Electric Angels','Cherry Static','Sugar Riot'],boy:['Midnight Avenue','Northstar','After Hours','Neon Saints','The Polaroids']};
  const roles=['Lead Vocalist','Dancer · Vocals','Rapper · Vocals','Harmony Vocalist'];
  const strengths=['Ambitious','Loyal','Charismatic','Creative','Fearless','Empathetic'];
  const flaws=['Jealous','Hot-headed','Party Animal','Insecure','Impulsive','Perfectionist'];
  const state={phase:'create',tab:'home',player:null,groupType:'girl',meetIndex:0,days:0,lastRecap:null,eventHistory:[],memberHistory:{},unlockFeed:[],hasTakenEmergencyLoan:false,debt:0,financialCrisis:false,careerStartDay:0,careerEndDay:null,peakFame:0,peakFans:0,careerEarnings:0,pendingWeek:false,milestones:{},pendingMilestones:[]};
  const activityData={
    studio:{icon:'🎙',title:'GO TO THE STUDIO',sub:'Record a new single',cost:8000,days:3,accent:'#ff4f9a'},
    show:{icon:'🎤',title:'PLAY A LOCAL SHOW',sub:'Win over a small crowd',cost:1500,days:2,accent:'#18aaa0'},
    photo:{icon:'📸',title:'BOOK A PHOTOSHOOT',sub:'Shape your public image',cost:4000,days:1,accent:'#efb90c'},
    promo:{icon:'📻',title:'DO A PRESS DAY',sub:'Radio, magazines and fan calls',cost:3000,days:2,accent:'#7540e8'},
    video:{icon:'📺',title:'SHOOT A MUSIC VIDEO',sub:'Give your single a visual',cost:15000,days:4,accent:'#ff4f9a',unlock:()=>bestPeak()<=40,require:'First reach the Top 40'},
    tv:{icon:'📡',title:'MTV APPEARANCE',sub:'Meet a national audience',cost:2500,days:2,accent:'#24bdb2',unlock:()=>S.fans>=10000,require:'Requires 10K fans'},
    tour:{icon:'🏟',title:'HEADLINE A TOUR',sub:'Take the show across the country',cost:30000,days:7,accent:'#ff796f',unlock:()=>S.fans>=250000,require:'Requires 250K fans'},
    awards:{icon:'🏆',title:'ATTEND AN AWARD SHOW',sub:'One night can change everything',cost:5000,days:1,accent:'#e6b51a',unlock:()=>S.fame>=60,require:'Requires higher Fame'}
  };
  const events=[
    {id:'pager',time:'2:13 AM',title:'YOUR PAGER GOES OFF.',body:m=>`It’s ${m.name}. “${S.members[1]?.name||'Jade'} hasn’t come home. Don’t tell the manager.”`,choices:[
      ['CALL THEM','You find them outside a club and bring them home.',{heart:10,chem:4}],
      ['TELL THE MANAGER','The manager handles it. Your bandmate feels betrayed.',{heart:-14,fame:2}],
      ['IGNORE IT','Morning rehearsal is a disaster.',{chem:-9,hype:4}]]},
    {id:'mtv',time:'YOUR MANAGER IS CALLING',title:'MTV WANTS THE BAND. TONIGHT.',body:m=>`${m.name} says they’re too sick to go. The car arrives in twenty minutes.`,requires:()=>S.fans>=5000,choices:[
      ['GO WITHOUT THEM','The interview works, but the empty chair becomes the story.',{hype:10,heart:-12}],
      ['CANCEL THE APPEARANCE','The band closes ranks. MTV is not impressed.',{chem:8,hype:-8}],
      ['TELL THEM THEY HAVE TO COME','They smile on camera and refuse to speak to you after.',{fame:6,heart:-16}]]},
    {id:'tabloid',time:'THE MORNING PAPERS',title:'YOU ARE THE FRONT PAGE.',body:()=>`A photographer caught you leaving a nightclub at 4AM. The headline is brutal.`,requires:()=>S.fame>=10,choices:[
      ['IGNORE IT','Mystery feeds the story. The others hate the distraction.',{hype:12,chem:-4}],
      ['APOLOGIZE','The story cools down, but so does the buzz.',{fame:4,hype:-5}],
      ['LEAN INTO IT 😈','Your new image explodes—and splits the band.',{hype:18,chem:-10}]]},
    {id:'jealous',time:'AFTER REHEARSAL',title:'“WHY AM I EVEN IN THIS GROUP?”',body:m=>`${m.name} says you always get the spotlight, then slams the dressing-room door.`,choices:[
      ['LISTEN TO THEM','You stay until both of you finally say the truth.',{heart:12,chem:5}],
      ['DEFEND YOURSELF','You win the argument. You lose the room.',{heart:-12,fame:3}],
      ['PROMISE A DUET','A new arrangement gives you both a moment.',{cash:-2500,heart:7,chem:5}]]}
  ];
  const app=document.createElement('main');app.id='popLifeApp';app.className='life-app';document.body.append(app);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const money=n=>'$'+Math.max(0,Math.round(n)).toLocaleString();
  const monthShort=()=>months[S.month].slice(0,3).toUpperCase();
  const bestPeak=()=>S.songs.length?Math.min(...S.songs.filter(x=>x.released).map(x=>x.peak),100):100;
  const titleLevel=()=>S.fans>=1000000?'GLOBAL ICON':S.fans>=250000?'SUPERSTAR':S.fans>=50000?'POP STAR':S.fans>=10000?'RISING STAR':S.fans>=1000?'LOCAL BUZZ':'UNKNOWN';
  const sceneClass=()=>S.fans>=50000?'star':S.fans>=5000?'rising':'unknown';
  function save(){trackCareer();try{localStorage.setItem(SAVE_KEY,JSON.stringify({state,S:{band:S.band,month:S.month,year:S.year,week:S.week,cash:S.cash,fans:S.fans,hype:S.hype,chem:S.chem,fame:S.fame,songs:S.songs,members:S.members,feed:S.feed}}))}catch(e){}}
  function restore(){try{meta={...meta,...JSON.parse(localStorage.getItem(META_KEY)||'{}')};}catch(e){} try{const saved=JSON.parse(localStorage.getItem(SAVE_KEY));if(!saved)return;Object.assign(state,saved.state||{});Object.assign(S,saved.S||{})}catch(e){}}
  function generateMembers(){resetCareerFields();const pool=[...firstNames[state.groupType]].sort(()=>Math.random()-.5);S.members=pool.slice(0,state.groupType==='girl'?3:4).map((name,i)=>({name,age:18+Math.floor(Math.random()*7),role:roles[i%roles.length],trait:strengths[i%strengths.length],strength:strengths[i%strengths.length],flaw:flaws[(i+2)%flaws.length],heart:45+Math.floor(Math.random()*16),wellbeing:80,v:65+Math.floor(Math.random()*29),s:65+Math.floor(Math.random()*29),c:65+Math.floor(Math.random()*29),color:['#ff4f93','#9064dc','#20c9bd','#ff9650'][i]}));S.band=bandNames[state.groupType][Math.floor(Math.random()*bandNames[state.groupType].length)];S.chem=72;S.cash=50000;S.fans=0;S.fame=0;S.hype=5;S.songs=[];S.month=0;S.week=1;S.year=1;Object.fromEntries(S.members.map(m=>[m.name,[]]));state.memberHistory={};S.members.forEach(m=>state.memberHistory[m.name]=[])}
  function shell(content){return `<section class="shell"><header class="top-hud"><b>${monthShort()} ${1996+S.year} · WEEK ${S.week}</b><span class="hud-chip">${money(S.cash)}</span><span class="hud-chip">★ ${S.fans.toLocaleString()}</span></header>${content}<nav class="bottom-nav">${[['home','⌂','HOME'],['career','✦','CAREER'],['music','♫','MUSIC'],['band','♥','BAND'],['you','☺','YOU']].map(([id,ic,l])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}"><i>${ic}</i>${l}</button>`).join('')}</nav></section>`}
  function renderCreate(){app.innerHTML=`<section class="life-screen setup"><div class="eyeline">WELCOME TO 1997</div><h1 class="story-title">YOUR SHOT AT<br><em>POP STARDOM</em></h1><p class="story-copy">One audition. One group. One chance to become unforgettable.</p><div class="setup-form"><label class="field"><span>YOUR NAME</span><input id="playerName" maxlength="18" placeholder="Enter your name" value="${esc(state.player?.name||'Alex')}"></label><label class="field"><span>AGE</span><select id="playerAge">${Array.from({length:7},(_,i)=>`<option ${state.player?.age===18+i?'selected':''}>${18+i}</option>`).join('')}</select></label><span class="choice-label">GROUP TYPE</span><div class="segmented" data-group><button data-group-type="girl" class="${state.groupType==='girl'?'active':''}">GIRL GROUP</button><button data-group-type="boy" class="${state.groupType==='boy'?'active':''}">BOY BAND</button></div><span class="choice-label" style="margin-top:19px">YOUR ROLE</span><div class="role-grid">${[['voice','THE VOICE','Great vocals · Average dancing'],['performer','THE PERFORMER','Great dancing · Average vocals'],['heartthrob','THE HEARTTHROB','High fan appeal · Big ego'],['artist','THE ARTIST','Songwriter · Shy with publicity']].map((r,i)=>`<button class="role-card ${(state.player?.role||'voice')===r[0]?'active':''}" data-role="${r[0]}"><b>${r[1]}</b><small>${r[2]}</small></button>`).join('')}${meta.unlockedRoles.includes('wild')?`<button class="role-card ${state.player?.role==='wild'?'active':''}" data-role="wild"><b>THE WILD ONE</b><small>Unlocked · Live on your own terms</small></button>`:'<button class="role-card locked" disabled><b>THE WILD ONE 🔒</b><small>Finish your first career</small></button>'}<button class="role-card locked" disabled><b>THE ICON 🔒</b><small>Complete one career</small></button></div><button class="primary" id="startStory">START MY STORY →</button></div></section>`;bindCreate()}
  function bindCreate(){app.querySelectorAll('[data-group-type]').forEach(b=>b.onclick=()=>{state.groupType=b.dataset.groupType;renderCreate()});app.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{state.player={...(state.player||{}),role:b.dataset.role};renderCreate()});app.querySelector('#startStory').onclick=()=>{const name=app.querySelector('#playerName').value.trim()||'Alex';const age=+app.querySelector('#playerAge').value;state.player={name,age,role:state.player?.role||'voice'};generateMembers();state.phase='meet';state.meetIndex=0;save();render()}}
  function memberDescription(m){const map={Jealous:'They notice every glance and every solo.','Hot-headed':'They feel everything fast—and loudly.','Party Animal':'They can turn any night into a story.','Insecure':'They hide their doubts behind perfect rehearsals.',Impulsive:'They act first and explain later.',Perfectionist:'Good is never quite good enough.'};return `“${m.trait} when it matters. ${map[m.flaw]}”`}
  function renderMeet(){if(state.meetIndex<S.members.length){const m=S.members[state.meetIndex];app.innerHTML=`<section class="life-screen meet"><div class="eyeline">AUDITION DAY · ${state.meetIndex+1} OF ${S.members.length}</div><article class="polaroid"><div class="member-photo" style="--member-color:${m.color}" data-letter="${m.name[0]}"><span class="photo-tag">MEET ${esc(m.name.toUpperCase())}</span></div><h2>${esc(m.name)}</h2><p class="meta">${esc(m.role)} · ${m.age}</p><p class="quote">${esc(memberDescription(m))}</p><div class="traits"><span>${esc(m.strength.toUpperCase())}</span><span>${esc(m.flaw.toUpperCase())}</span></div><div class="relationship">❤️ RELATIONSHIP · ${m.heart}</div></article><button class="primary" id="nextMember">${state.meetIndex===S.members.length-1?'SEE YOUR BAND':'MEET THE NEXT MEMBER'} →</button></section>`;app.querySelector('#nextMember').onclick=()=>{state.meetIndex++;save();render()}}else{app.innerHTML=`<section class="life-screen meet"><div class="band-reveal"><div class="eyeline">YOUR BAND IS…</div><div class="record"><span>${esc(S.band.toUpperCase())}</span></div><h1 class="story-title">THIS IS<br><em>YOUR BEGINNING.</em></h1><div class="advance"><small>YOUR LABEL ADVANCE</small><b>$50,000</b><p>That’s everything you’ve got to record your debut single and get noticed.</p></div><button class="primary" id="beginLife">BEGIN →</button></div></section>`;app.querySelector('#beginLife').onclick=()=>{state.phase='game';state.tab='home';save();render()}}}
  function home(){const hasSong=S.songs.length>0, released=S.songs.some(s=>s.released);return `<div class="page-body"><section class="scene ${sceneClass()}"><span class="status-sticker">${titleLevel()}</span><h1 class="display">${esc(state.player.name)}<br><em>${esc(S.band)}</em></h1><p>${!hasSong?'Nobody knows your name yet. Your label wants a debut single.':!released?'Your first song is finished. Now the world needs to hear it.':'People are beginning to recognize you in the street.'}</p></section><section class="mission"><small>YOUR NEXT MOVE</small><h2>${!hasSong?'RECORD YOUR FIRST SINGLE':!released?'RELEASE YOUR DEBUT SINGLE':S.fans<10000?'GET PEOPLE TALKING':'KEEP THE MOMENT ALIVE'}</h2><p>${!hasSong?'The cheap studio is booked for three days. This could change everything.':!released?'It is sitting in your manager’s hands, ready to go.':'Fame is moving now. What you do next matters.'}</p><button class="action-cta" data-quick="${!hasSong?'studio':!released?'release':'career'}"><span>${!hasSong?'GO TO THE STUDIO · $8,000':!released?'RELEASE IT':'CHOOSE AN OPPORTUNITY'}</span><b>→</b></button></section><div class="life-list"><div class="life-note"><i>📟</i><span><b>${S.feed[0]||'Your pager is quiet.'}</b><small>The latest thing everyone is talking about.</small></span></div><div class="life-note"><i>♥</i><span><b>${S.chem>=75?'The group feels close.':S.chem>=50?'There is some tension in rehearsal.':'Nobody is speaking after rehearsal.'}</b><small>Your choices shape the people around you.</small></span></div>${S.songs.some(s=>s.released)?`<div class="life-note"><i>📻</i><span><b>Your single is currently #${S.songs.find(s=>s.released).pos}.</b><small>Anything can happen when the next week begins.</small></span></div>`:''}</div></div>`}
  function career(){return `<div class="page-body"><span class="section-kicker">YOUR NEXT MOVE</span><h1 class="page-heading">WHAT DO YOU<br>WANT TO DO?</h1><p class="page-intro">Every opportunity takes time. Some consequences only reveal themselves later.</p><div class="opportunity-list">${Object.entries(activityData).map(([id,a])=>{const unlocked=!a.unlock||a.unlock();const affordable=S.cash>=a.cost;return `<button class="opportunity ${unlocked?'':'locked'}" data-activity="${id}" ${!unlocked||!affordable?'disabled':''} style="--accent:${a.accent}"><span class="icon">${a.icon}</span><span><b>${a.title}${unlocked?'':' 🔒'}</b><small>${a.sub}</small>${!unlocked?`<small class="unlock-note">${a.require}</small>`:!affordable?'<small class="unlock-note">Not enough money</small>':''}</span><em>${a.cost?money(a.cost):'FREE'}</em></button>`}).join('')}</div></div>`}
  function music(){if(!S.songs.length)return `<div class="page-body"><span class="section-kicker">YOUR MUSIC</span><h1 class="page-heading">EVERY DYNASTY<br>STARTS WITH ONE SONG.</h1><div class="empty-state"><div class="disc"></div><p class="page-intro">You have no releases yet. The studio is waiting.</p><button class="primary" data-activity="studio">RECORD YOUR DEBUT SINGLE</button></div>${futureContent()}</div>`;const released=S.songs.filter(s=>s.released);return `<div class="page-body"><span class="section-kicker">YOUR MUSIC</span><h1 class="page-heading">THE SONGS<br>THAT TELL YOUR STORY.</h1><div class="release-list">${S.songs.map((s,i)=>`<article class="release"><div class="cover">${esc(s.title[0])}</div><div><h3>${esc(s.title)}</h3><p>${s.released?`Released ${months[S.month]} ${1996+S.year}`:`Quality ${s.quality}/100 · Mastered`}</p>${s.released?`<p>Peak: #${s.peak} · Current: #${s.pos}${s.lastPos&&s.pos<s.lastPos?' ↑':''}</p><p>Sales: ${Math.max(1,Math.round((s.sales||S.fans*.55)/1000))}K</p>`:`<button class="release-btn" data-release="${i}">RELEASE SINGLE</button>`}</div></article>`).join('')}</div>${released.length?chartContent():''}${futureContent()}</div>`}
  function futureContent(){return `<div class="future-row"><div class="future">ALBUMS 🔒 · Unlock after 3 singles</div><div class="future">MUSIC VIDEOS ${bestPeak()<=40?'✓':'🔒 · Reach the Top 40'}</div><div class="future">TOUR SETLIST 🔒 · Unlock later</div></div>`}
  function chartContent(){const mine=S.songs.filter(s=>s.released).map(s=>({pos:s.pos,title:s.title,player:true}));const others=rivals.slice(0,7).map((r,i)=>({pos:[1,4,8,12,19,27,39][i],title:r[1]}));return `<section class="chart-sheet"><h3>THE WEEKLY TOP 10</h3>${[...mine,...others].sort((a,b)=>a.pos-b.pos).slice(0,10).map(x=>`<div class="chart-row ${x.player?'player':''}"><b>${x.pos}</b><span>${esc(x.title)}</span><small>${x.player?'YOUR SINGLE':'—'}</small></div>`).join('')}</section>`}
  function relationText(n){return n>=80?'You’ve become close.':n>=60?'Things are good.':n>=40?'Things are okay.':n>=20?'There’s tension between you.':'They barely look at you.'}
  function band(){return `<div class="page-body"><span class="section-kicker">THE PEOPLE BESIDE YOU</span><h1 class="page-heading">THE BAND</h1><div class="group-shot"><b class="chemistry">CHEMISTRY ❤️ ${S.chem}</b></div><div class="member-list">${S.members.map((m,i)=>`<button class="relationship-card" data-member="${i}"><header><h3>${esc(m.name)}</h3><b>❤️ ${m.heart}</b></header><p>${relationText(m.heart)}</p><div class="member-detail hidden-life"><div class="traits"><span>${esc(m.strength.toUpperCase())}</span><span>${esc(m.flaw.toUpperCase())}</span></div><b>RECENT HISTORY</b><ul class="history">${(state.memberHistory[m.name]||['You met at the first audition.']).slice(-3).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></button>`).join('')}</div></div>`}
  function you(){return `<div class="page-body"><section class="profile-hero"><div class="avatar">${esc(state.player.name[0])}</div><h2>${esc(state.player.name)}</h2><div>${state.player.age} · ${roleName(state.player.role)}</div><p class="career-title">${titleLevel()}</p></section><div class="achievement-list"><div class="achievement"><b>★ FAME · ${S.fame}</b>${state.debt?`<small class="finance-debt">Label loan outstanding · ${money(state.debt)}</small>`:''}<p>Your public story is only beginning.</p></div><div class="achievement"><b>UNLOCKS</b><p>${bestPeak()<=40?'✓ Music videos':'🔒 Music videos · Reach the Top 40'}</p><p>${S.songs.length>=3?'✓ Albums':'🔒 Albums · Record 3 singles'}</p><p>${S.fans>=10000?'✓ TV appearances':'🔒 TV appearances · Reach 10K fans'}</p></div><div class="achievement"><b>CAREER HIGHLIGHTS</b><p>${S.songs.length} song${S.songs.length===1?'':'s'} recorded · ${S.fans.toLocaleString()} fans</p></div></div></div>`}
  function roleName(r){return {voice:'THE VOICE',performer:'THE PERFORMER',heartthrob:'THE HEARTTHROB',artist:'THE ARTIST',wild:'THE WILD ONE'}[r]||'THE VOICE'}
  function renderGame(){const views={home,career,music,band,you};app.innerHTML=shell(views[state.tab]());bindGame()}
  function bindGame(){app.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;save();render()});app.querySelectorAll('[data-activity]').forEach(b=>b.onclick=()=>perform(b.dataset.activity));app.querySelectorAll('[data-release]').forEach(b=>b.onclick=()=>releaseSong(+b.dataset.release));app.querySelectorAll('[data-member]').forEach(b=>b.onclick=()=>b.querySelector('.member-detail').classList.toggle('hidden-life'));const q=app.querySelector('[data-quick]');if(q)q.onclick=()=>q.dataset.quick==='release'?releaseSong(S.songs.findIndex(s=>!s.released)):q.dataset.quick==='career'?(state.tab='career',render()):perform(q.dataset.quick)}
  function perform(id){const a=activityData[id];if(state.phase!=='game'||state.pendingWeek||state.financialCrisis||!a||(a.unlock&&!a.unlock())||S.cash<a.cost)return;if(id==='studio')return studioModal();S.cash-=a.cost;let msg='';if(id==='show'){const gain=400+Math.round(Math.random()*900);S.fans+=gain;S.chem=clamp(S.chem+2);msg=`A tiny club sings the chorus back. +${gain.toLocaleString()} fans.`}if(id==='photo'){S.fame=clamp(S.fame+4);S.hype=clamp(S.hype+7);msg='The photos look like the future you imagined.'}if(id==='promo'){S.hype=clamp(S.hype+13);S.fans+=700;msg='Your first radio interview has people asking who you are.'}if(id==='video'){S.hype=clamp(S.hype+18);S.fame=clamp(S.fame+7);S.fans+=2400;msg='Your video premieres. For three minutes, the world feels yours.'}if(id==='tv'){S.fame=clamp(S.fame+10);S.fans+=6500;msg='The MTV cameras find you. By morning, strangers know your face.'}if(id==='tour'){S.fame=clamp(S.fame+15);S.fans+=42000;receiveIncome(18000);msg='The tour changes the scale of everything.'}if(id==='awards'){S.fame=clamp(S.fame+12);S.fans+=12000;msg='Every flashbulb makes the dream feel real.'}if(id==='tv')addMilestone('tv','YOUR FIRST MTV APPEARANCE! 📺');if(id==='awards')addMilestone('award','YOUR FIRST AWARD SHOW! 🏆');S.feed.unshift(msg);advanceTime(a.days,msg,['promo','video','tv','tour','awards'].includes(id)?'important':'normal');save()}
  function studioModal(){toastQueue?.setBlocked(true);app.insertAdjacentHTML('beforeend',`<div class="story-overlay"><div class="story-inner"><div class="story-time">STUDIO A · 11:48 PM</div><h2>WHAT WILL YOUR<br>FIRST LINE SAY?</h2><p class="dialogue">The producer turns down the lights. This song could become the beginning of everything.</p><div class="result-card"><label class="field"><span>SONG TITLE</span><input id="mobileSongTitle" maxlength="28" value="Baby Don't Go"></label><button class="primary" id="recordMobile">RECORD · $8,000</button><button class="primary" style="background:#ddd2c5;color:#17132b;box-shadow:none" id="cancelMobile">NOT YET</button></div></div></div>`);app.querySelector('#cancelMobile').onclick=()=>{app.querySelector('.story-overlay').remove();toastQueue?.setBlocked(false)};app.querySelector('#recordMobile').onclick=()=>{const title=app.querySelector('#mobileSongTitle').value.trim();if(!title||S.cash<8000)return;S.cash-=8000;const roleBonus=state.player.role==='voice'?8:state.player.role==='artist'?10:state.player.role==='performer'?4:2;const quality=Math.min(99,67+roleBonus+Math.floor(Math.random()*15));S.songs.push({title,quality,catchy:68+Math.floor(Math.random()*23),released:false,pos:100,peak:100,weeks:0,sales:0});S.hype=clamp(S.hype+5);const msg=`“${title}” is finished. Quality: ${quality}/100.`;S.feed.unshift(msg);app.querySelector('.story-overlay').remove();advanceTime(3,msg);save()}}
  function releaseSong(i){const song=S.songs[i];if(state.phase!=='game'||state.pendingWeek||state.financialCrisis||!song||song.released)return;song.released=true;song.pos=Math.max(42,72-Math.round((song.quality+S.hype)/12));song.peak=song.pos;song.weeks=1;song.lastPos=100;S.hype=clamp(S.hype+10);const gain=900+Math.round(song.quality*15);S.fans+=gain;const msg=`“${song.title}” enters the chart at #${song.pos}.`;S.feed.unshift(msg);advanceTime(2,msg);save()}
  function advanceTime(days,msg,level='normal'){state.days+=days;collectMilestones();if(!state.pendingMilestones.length)showToast(`${msg} · ${days} day${days===1?'':'s'} pass.`,level);if(state.days>=7){state.days-=7;state.pendingWeek=true;save();render();weekTimer=setTimeout(newWeek,850)}else{state.tab='home';render()}}
  function newWeek(){if(state.phase!=='game')return;state.pendingWeek=false;weekTimer=null;const oldPositions={};S.songs.filter(s=>s.released).forEach(s=>oldPositions[s.title]=s.pos);S.week++;if(S.week>4){S.week=1;S.month++;if(S.month>11){S.month=0;S.year++}}let biggest=null;let earned=0;let newFans=120+Math.round(S.hype*18);S.songs.filter(s=>s.released).forEach(s=>{s.lastPos=s.pos;const climb=Math.max(1,Math.round((s.quality+s.catchy+S.hype)/24+Math.random()*5));s.pos=Math.max(1,s.pos-climb);s.peak=Math.min(s.peak,s.pos);s.weeks++;const songFans=Math.max(500,Math.round((101-s.pos)*35));newFans+=songFans;s.sales=(s.sales||0)+Math.round(songFans*1.7);const royalties=Math.min(6000,Math.round(songFans*.22));receiveIncome(royalties);earned+=royalties;if(!biggest||climb>biggest.climb)biggest={song:s,old:oldPositions[s.title],climb};if(s.pos===1&&s.lastPos!==1){addMilestone('numberOne','YOUR FIRST #1 SINGLE! 🏆');S.fame=clamp(S.fame+18);S.hype=clamp(S.hype+15)}});S.fans+=newFans;S.hype=clamp(S.hype-2);collectMilestones();state.lastRecap={newFans,biggest,earned,milestones:[...state.pendingMilestones]};save();if(checkFinancialCrisis())return;showRecap()}
  function showRecap(){toastQueue?.setBlocked(true);const r=state.lastRecap;app.insertAdjacentHTML('beforeend',`<div class="recap-overlay"><div class="recap"><div class="week-big">${monthShort()} ${1996+S.year} · WEEK ${S.week}</div><h2>${r.biggest?'YOUR SINGLE CLIMBED':'A NEW WEEK BEGINS'}</h2>${r.biggest?`<div class="movement">#${r.biggest.old} → #${r.biggest.song.pos}</div>`:''}<p>+${r.newFans.toLocaleString()} new fans</p><p class="recap-earned">+${money(r.earned||0)} earned</p>${(r.milestones||[]).map(m=>`<p class="recap-milestone">${esc(m)}</p>`).join('')}<button class="primary" id="continueWeek">SEE WHAT HAPPENS →</button></div></div>`);app.querySelector('#continueWeek').onclick=()=>{app.querySelector('.recap-overlay').remove();state.pendingMilestones=[];save();if(checkFinancialCrisis())return;const event=pickEvent();if(event)showEvent(event);else{state.tab='home';render()}}}
  function pickEvent(){if(Math.random()>.72)return null;const pool=events.filter(e=>(!e.requires||e.requires())&&state.eventHistory.at(-1)!==e.id);return pool[Math.floor(Math.random()*pool.length)]}
  function showEvent(event){toastQueue?.setBlocked(true);const member=[...S.members].sort((a,b)=>a.heart-b.heart)[0];state.eventHistory.push(event.id);app.innerHTML=`<div class="story-overlay"><div class="story-inner"><div class="story-time">${event.time}</div><div class="pager"><span>CALLING…<br>${esc(member.name.toUpperCase())}</span></div><h2>${event.title}</h2><p class="dialogue">${esc(event.body(member))}</p><div class="story-choices">${event.choices.map((c,i)=>`<button data-event-choice="${i}">${c[0]}</button>`).join('')}</div></div></div>`;app.querySelectorAll('[data-event-choice]').forEach(b=>b.onclick=()=>resolveEvent(event,+b.dataset.eventChoice,member))}
  function resolveEvent(event,index,member){const [label,outcome,e]=event.choices[index];if(e.cash>0)receiveIncome(e.cash);else if(e.cash)S.cash=Math.max(0,S.cash+e.cash);if(e.heart){member.heart=clamp(member.heart+e.heart);(state.memberHistory[member.name]||=[]).push(`${e.heart>0?'✓':'✕'} ${outcome}`)}if(e.chem)S.chem=clamp(S.chem+e.chem);if(e.fame)S.fame=clamp(S.fame+e.fame);if(e.hype)S.hype=clamp(S.hype+e.hype);S.feed.unshift(outcome);save();if(checkFinancialCrisis())return;app.innerHTML=`<div class="story-overlay"><div class="story-inner"><div class="story-time">DECISION MADE</div><div class="result-card"><h2>${label}</h2><p>${outcome}</p><div class="result-deltas">${Object.entries(e).map(([k,v])=>`<span>${k.toUpperCase()} ${v>0?'+':''}${v}</span>`).join('')}</div><button class="primary" id="eventContinue">CONTINUE MY STORY →</button></div></div></div>`;app.querySelector('#eventContinue').onclick=()=>{state.tab='home';render()}}
  function showToast(text,level='normal'){toastQueue?.push(text,level)}
  function addMilestone(id,text){if(state.milestones[id])return;state.milestones[id]=true;state.pendingMilestones.push(text)}
  function collectMilestones(){if(S.fans>=100000)addMilestone('fans100k','100,000 FANS! ★');if(S.fans>=50000)addMilestone('popStar','YOU ARE A POP STAR! ★')}
  function showPendingMilestones(){
    if(!state.pendingMilestones.length||state.pendingWeek||state.phase!=='game')return false;
    toastQueue?.setBlocked(true);
    app.insertAdjacentHTML('beforeend',`<div class="recap-overlay"><div class="recap"><div class="week-big">A MOMENT TO REMEMBER</div>${state.pendingMilestones.map(m=>`<h2>${esc(m)}</h2>`).join('')}<button class="primary" id="milestoneContinue">CONTINUE MY STORY →</button></div></div>`);
    app.querySelector('#milestoneContinue').onclick=()=>{state.pendingMilestones=[];save();render()};return true;
  }
  function initializeFeedback(){
    toastQueue=PopFeedback.createToastQueue({show(text,level,dismiss){
      const node=document.createElement('div');node.className='toast toast-enter'+(level==='important'?' toast-important':'');node.textContent=text;node.setAttribute('role','status');node.setAttribute('aria-live','polite');node.setAttribute('tabindex','0');node.onclick=dismiss;node.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();dismiss()}};document.body.append(node);
      return {exit(){node.classList.add('toast-exit')},remove(){node.remove()},setHidden(value){node.hidden=value}};
    }});
  }
  function render(){if(state.phase==='ended'){renderEnding();return;}if(state.phase==='game'&&checkFinancialCrisis())return;if(state.phase==='create')renderCreate();else if(state.phase==='meet')renderMeet();else{renderGame();if(showPendingMilestones())return;toastQueue?.setBlocked(state.pendingWeek);if(state.pendingWeek)app.insertAdjacentHTML('beforeend','<div class="recap-overlay"><div class="recap"><div class="week-big">THE WEEK IS CHANGING…</div><h2>YOUR STORY<br>KEEPS MOVING.</h2></div></div>')}}

  function careerDay(){return (S.year-1)*336+S.month*28+(S.week-1)*7+state.days+(state.pendingWeek?7:0)}
  function dateLabel(day){const year=1997+Math.floor(day/336);const month=Math.floor(day%336/28);return `${months[month].slice(0,3).toUpperCase()} ${year} · DAY ${day%28+1}`}
  function trackCareer(){if(state.phase==='game'||state.phase==='ended'){state.peakFame=Math.max(state.peakFame||0,S.fame);state.peakFans=Math.max(state.peakFans||0,S.fans)}}
  function receiveIncome(amount){S.cash+=amount;state.careerEarnings=(state.careerEarnings||0)+Math.max(0,amount)}
  // Shared availability rules: a release is free; queued time must finish before failure.
  // Royalty income is NOT independently available: it requires time progression.
  // Register future free activities/rewards here with their actual availability predicate.
  const progressionMechanics=[
    ()=>Object.values(activityData).some(a=>(!a.unlock||a.unlock())&&S.cash>=(a.cost||0)),
    ()=>S.songs.some(song=>!song.released),
    ()=>state.pendingWeek
  ];
  function hasValidProgressionPath(){return progressionMechanics.some(available=>available())}
  function checkFinancialCrisis(){
    if(state.phase!=='game')return false;
    if(hasValidProgressionPath()){state.financialCrisis=false;return false;}
    if(state.hasTakenEmergencyLoan){endCareer();return true;}
    state.financialCrisis=true;save();renderCrisis();return true;
  }
  function renderCrisis(){toastQueue?.setBlocked(true);
    app.innerHTML=`<div class="story-overlay"><div class="story-inner"><div class="story-time">YOUR MANAGER IS CALLING</div><div class="pager"><span>LAST CHANCE</span></div><h2>YOU'RE BROKE.</h2><p class="dialogue">The label advance is gone.<br>You barely have enough money to keep the dream alive.</p><p class="dialogue">Your manager has one last option:<br>Take a $30,000 emergency loan.</p><div class="story-choices"><button id="takeEmergencyLoan">TAKE THE LOAN — $30,000<small class="finance-last-chance">“This is your last chance.”</small></button><button id="walkAway">WALK AWAY</button></div></div></div>`;
    app.querySelector('#takeEmergencyLoan').onclick=takeEmergencyLoan;
    app.querySelector('#walkAway').onclick=endCareer;
  }
  function takeEmergencyLoan(){
    if(state.phase!=='game'||state.hasTakenEmergencyLoan||!state.financialCrisis)return;
    S.cash+=30000;state.hasTakenEmergencyLoan=true;state.debt=30000;state.financialCrisis=false;
    S.feed.unshift('Your manager secured one last loan. The story is not over.');
    save();render();
  }
  function endCareer(){
    if(state.phase==='ended')return;
    trackCareer();state.careerEndDay=careerDay();state.phase='ended';state.financialCrisis=false;
    state.pendingWeek=false;if(weekTimer)clearTimeout(weekTimer);weekTimer=null;
    meta.completedCareers++;state.newRoleUnlocked=!meta.unlockedRoles.includes('wild');
    if(state.newRoleUnlocked)meta.unlockedRoles.push('wild');
    try{localStorage.setItem(META_KEY,JSON.stringify(meta))}catch(e){}
    save();renderEnding();
  }
  function renderEnding(){toastQueue?.setBlocked(true);
    const released=S.songs.filter(s=>s.released);const highest=released.length?Math.min(...released.map(s=>s.peak)):'—';
    const stats=[['Peak Fame',state.peakFame],['Peak Fans',(state.peakFans||0).toLocaleString()],['Singles Released',released.length],['Highest Chart Position',highest==='—'?highest:'#'+highest],['Final Band Chemistry',S.chem],['Career Earnings',money(state.careerEarnings||0)],['Career Length',Math.max(0,state.careerEndDay-state.careerStartDay)+' days']];
    app.innerHTML=`<div class="story-overlay"><div class="story-inner finance-ending"><div class="story-time">THE FINAL PAGE</div><h2>THE DREAM<br>IS OVER.</h2><p class="finance-dates">${dateLabel(state.careerStartDay)} — ${dateLabel(state.careerEndDay)}</p><p class="dialogue">${esc(S.band)} couldn't keep going.<br>The money is gone and the label has pulled its support.</p><p class="dialogue">But for a while... people knew your name.</p><div class="result-card"><h3>YOUR POP DYNASTY</h3><dl class="finance-summary">${stats.map(([label,value])=>`<div><dt>${label}</dt><dd>${value}</dd></div>`).join('')}</dl>${state.newRoleUnlocked?'<p class="finance-unlock"><small>NEW ROLE UNLOCKED</small><br><b>THE WILD ONE</b></p>':''}<button class="primary" id="newStory">START A NEW STORY →</button></div></div></div>`;
    app.querySelector('#newStory').onclick=startNewStory;
  }
  function resetCareerFields(){
    Object.assign(state,{days:0,lastRecap:null,eventHistory:[],memberHistory:{},unlockFeed:[],hasTakenEmergencyLoan:false,debt:0,financialCrisis:false,careerStartDay:0,careerEndDay:null,peakFame:0,peakFans:0,careerEarnings:0,pendingWeek:false,milestones:{},pendingMilestones:[],newRoleUnlocked:false});
    S.actions=3;S.event=false;S.delayedConsequences=[];S.eventHistory=[];S.nextSongBonus=0;S.pendingEventId=null;
    S.feed=['A tiny label has taken a chance on your new group.','Your first rehearsal starts today.'];
  }
  function startNewStory(){toastQueue?.clear();
    if(weekTimer)clearTimeout(weekTimer);weekTimer=null;resetCareerFields();
    Object.assign(state,{phase:'create',tab:'home',player:null,groupType:'girl',meetIndex:0});
    Object.assign(S,{cash:50000,fans:0,fame:0,hype:5,chem:72,songs:[],members:[],band:'',month:0,week:1,year:1});
    save();render();
  }

  restore();
  // Migrate old careers without replaying milestones they already achieved.
  let prior=null;try{prior=JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch(e){}
  if(prior&&!prior.state?.milestones){state.milestones={numberOne:S.songs.some(s=>s.released&&s.peak===1),fans100k:S.fans>=100000,popStar:S.fans>=50000};}
  initializeFeedback();render();if(state.pendingWeek&&state.phase==='game')weekTimer=setTimeout(newWeek,850);
})();
